an overdue update... all steps verified to run on a clean linux image.

diff --git a/BUILDING-UPDATES b/BUILDING-UPDATES
--- a/BUILDING-UPDATES
+++ b/BUILDING-UPDATES
@@ -1,54 +1,108 @@
 # #############################################################################
 # THIS DOCUMENT DESCRIBES HOW TO UPGRADE THE EXTERNAL PACKAGES.
 # It's a living doc, and may/will contain errors!
-# To be honest: it's terrible... I hope to clean it up one day.
-# It's also done on cygwin... again, I will clean/migrate this to Linux one day.
+# To be honest: it's too complicated... I hope to clean it up one day.
 # #############################################################################
 
-Prerequisites: see BUILDING and "build.sh"
+# Prerequisites: see BUILDING and "build.sh"
+# It is assumed you already have git setup for your user.
 
-- RSYNC    - https://rsync.samba.org/
-- OPENSSH  - https://github.com/openssh/openssh-portable
-- DROPBEAR - https://matt.ucc.asn.au/dropbear/dropbear.html
+# If you don't have the autoconf command, install it with:
+sudo apt install autoconf
 
-# ############################################################################
-# Environment as typically set in ~/.bashrc
-# ############################################################################
+# #############################################################################
+# Define the versions for the external project code; update the urls if needed
+# #############################################################################
+
+# RSYNC    - https://rsync.samba.org/
+# OPENSSH  - https://github.com/openssh/openssh-portable
+# DROPBEAR - https://matt.ucc.asn.au/dropbear/dropbear.html
+#            Note we use the mirror at https://dropbear.nl due to asn.au
+#            giving consistent TLS issues (too strict for wget?)
+
+export RSYNC_VERSION="rsync-3.4.2"
+export OPENSSH_VERSION="openssh-10.3p1"
+export DROPBEAR_VERSION="dropbear-2026.91"
+
+export RSYNC_DOWNLOAD="https://download.samba.org/pub/rsync/src/${RSYNC_VERSION}.tar.gz"
+export OPENSSH_DOWNLOAD="https://mirror.ox.ac.uk/pub/OpenBSD/OpenSSH/portable/${OPENSSH_VERSION}.tar.gz"
+export DROPBEAR_DOWNLOAD="https://dropbear.nl/mirror/releases/${DROPBEAR_VERSION}.tar.bz2"
+
+# #############################################################################
+# Java must be version 21 or higher
+# This can be skipped if the java 21 bin directory is already in your path.
+# #############################################################################
 
 export JAVA_HOME=/cygdrive/c/d/jdk/
 export PATH=${JAVA_HOME}/bin:${PATH}
 
+# #############################################################################
+# Define the physical locations.
+# #############################################################################
+
+# The root directory of the Ssh4d project (i.e. where the projects .git is)
+export PROJECT_ROOT=~/Sshd4a
+
+# The temp working directory where the tarballs will be downloaded and git remotes will be setup.
+export SRC_ROOT=~/tmp/sshd4a-tarballs
+
 # Android SDK location
-SDK=/cygdrive/c/d/sdk
+export ANDROID_HOME=~/android-sdk
+
+# #############################################################################
+# SDK and NDK versions
+# #############################################################################
 
 # Android NDK location/version; upgrade as needed/wanted
 # This must also be updated in gradle/libs.versions.toml
-NDK=${SDK}/ndk/30.0.14904198
+export ANDROID_NDK=${ANDROID_HOME}/ndk/30.0.14904198
 
 # Android minSdkVersion. The minimal version, upgrade as needed/wanted
 export ANDROID_MIN_SDK=30
 
-# Only choose ONE of these, depending on your device...
-# the first, "aarch64", is most likely the one you want.
+# #############################################################################
+# Build platform
+# #############################################################################
+
+# Only choose ONE of these, depending on your device.
+# The first, "aarch64", is most likely the one you want.
 export ANDROID_TARGET=aarch64-linux-android
 # export ANDROID_TARGET=armv7a-linux-androideabi
 # export ANDROID_TARGET=i686-linux-android
 # export ANDROID_TARGET=x86_64-linux-android
 
-export TOOLCHAIN=${NDK}/toolchains/llvm/prebuilt/windows-x86_64
-export PATH=${SDK}/platform-tools:${TOOLCHAIN}/bin:${PATH}
+# The native platform
+export TOOLCHAIN=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64
+# export TOOLCHAIN=${ANDROID_NDK}/toolchains/llvm/prebuilt/windows-x86_64
 
-# ############################################################################
-# Setting up the toolchain; add to bashrc, or run manually
-# ############################################################################
+# #############################################################################
+# Below this point, no configuration changes needed
+# #############################################################################
 
-# Sanity checks for the .bashrc settings.
-# TOOLCHAIN is expected to point to your ndk environment toolchain.
-[ -n "${TOOLCHAIN}" ] || { echo "TOOLCHAIN must be set"; exit 1; }
+# Sanity checks.
+if ! command -v java >/dev/null 2>&1; then
+    echo "Error: 'java' not found in your PATH."
+    exit 1
+fi
 
-if [ ! -d "$NDK" ]; then
-  echo "$NDK does not exist."
-  exit 1
+# Need 21 or up
+JAVA_VER=$(java --version | head -n 1 | awk '{print $2}' | cut -d. -f1)
+if [ -z "$JAVA_VER" ] || [ "$JAVA_VER" -lt 21 ]; then
+    echo "Error: Java 21 is required. Found version: ${JAVA_VER:-unknown}"
+    exit 1
+fi
+
+if [ -z "${ANDROID_NDK}" ]; then
+    echo "ANDROID_NDK is not set or is empty."
+    exit 1
+fi
+if [ ! -d "${ANDROID_NDK}" ]; then
+    echo "${ANDROID_NDK} does not exist."
+    exit 1
+fi
+if [ -z "${TOOLCHAIN}" ]; then
+    echo "TOOLCHAIN is not set or is empty."
+    exit 1
 fi
 
 export AR=${TOOLCHAIN}/bin/llvm-ar
@@ -62,62 +116,45 @@ export STRIP=${TOOLCHAIN}/bin/llvm-strip
 # content for ".gitattributes"
 export GATRR="* text eol=lf\n*.txt text\n*.png binary\n*.jar binary\n"
 
-# #############################################################################
-# Define the project root
-# #############################################################################
-
-# The root directory of the Ssh4d project (i.e. where the projects .git is)
-export PROJECT_ROOT=/cygdrive/c/Data/AndroidStudioProjects/Sshd4a/
+# add the tools to the path
+export PATH=${ANDROID_HOME}/platform-tools:${TOOLCHAIN}/bin:${PATH}
 
 # #############################################################################
-# Information dump
+# Configuration dump
 # #############################################################################
 echo Tools:
 echo JAVA_HOME=${JAVA_HOME}
-echo SDK=${SDK}
-echo NDK=${NDK}
+echo ANDROID_HOME=${ANDROID_HOME}
+echo ANDROID_NDK=${ANDROID_NDK}
 echo ANDROID_MIN_SDK=${ANDROID_MIN_SDK}
 echo ANDROID_TARGET=${ANDROID_TARGET}
 echo TOOLCHAIN=${TOOLCHAIN}
+
 echo Project:
 echo PROJECT_ROOT=${PROJECT_ROOT}
-
-# #############################################################################
-# Define the versions for the external project code; update the urls if changed
-# #############################################################################
-
-export RSYNC_VERSION="rsync-3.4.2"
-export OPENSSH_VERSION="openssh-10.3p1"
-export DROPBEAR_VERSION="dropbear-2026.91"
-
-export RSYNC_DOWNLOAD="https://download.samba.org/pub/rsync/src/${RSYNC_VERSION}.tar.gz"
-export OPENSSH_DOWNLOAD="https://mirror.ox.ac.uk/pub/OpenBSD/OpenSSH/portable/${OPENSSH_VERSION}.tar.gz"
-export DROPBEAR_DOWNLOAD="https://matt.ucc.asn.au/dropbear/releases/${DROPBEAR_VERSION}.tar.bz2"
-
-
-# The working directory where the tarballs will be downloaded and git remotes will be setup.
-export SRC_ROOT=/cygdrive/c/tmp/sshd4a-tarballs
+echo SRC_ROOT=${SRC_ROOT}
 
 # ############################################################################
 # Step 2.1 - RSYNC
 # ############################################################################
 
 cd ${SRC_ROOT}
-wget -q ${RSYNC_DOWNLOAD}
-unzip x -so ${RSYNC_VERSION}* | tar xf -
+export RSYNC="upstream-rsync"
+
+wget "${RSYNC_DOWNLOAD}" || { echo "Download failed. Exiting."; exit 1; }
+tar -xzf ${RSYNC_VERSION}.tar.gz
 
 # remove broken and/or unneeded rsync symlink
 rm ${RSYNC_VERSION}/md2man
 
 # rename the directory so we don't need to change the git remote names
-export RSYNC="upstream-rsync"
 mkdir -p ${RSYNC}/app/src/main/cpp/
 mv ${RSYNC_VERSION} ${RSYNC}/app/src/main/cpp/rsync
 
-# Prep rsync
+# Prepare a new repo
 cd ${RSYNC}
-echo -e "${GATRR}" >.gitattributes
-git init .
+printf "%b" "${GATRR}" > .gitattributes
+git init -b dev .
 git add * .gitattributes
 git commit -a -m "${RSYNC_VERSION}"
 cd ${SRC_ROOT}
@@ -129,9 +166,7 @@ cd ${SRC_ROOT}/${RSYNC}/app/src/main/cpp/rsync
             --disable-md2man --disable-roll-simd --disable-md5-asm --disable-roll-asm \
             --enable-largefile
 
-# ISSUE THE NEXT SET OF COMMANDS FROM THE TERMINAL INSIDE STUDIO
-# IF YOU ARE NOT THERE YET.
-
+# Switching to the project for merging.
 cd ${PROJECT_ROOT}
 
 # Add remote: "upstream-rsync" pointing to the location used above
@@ -165,18 +200,19 @@ cd ${PROJECT_ROOT}/app/src/main/cpp/
 # ############################################################################
 
 cd ${SRC_ROOT}
-wget -q ${OPENSSH_DOWNLOAD}
-unzip x -so ${OPENSSH_VERSION}* | tar xf -
+export OPENSSH="upstream-openssh"
+
+wget "${OPENSSH_DOWNLOAD}" || { echo "Download failed. Exiting."; exit 1; }
+tar -xzf ${OPENSSH_VERSION}.tar.gz
 
 # rename the directory so we don't need to change the git remote names
-export OPENSSH="upstream-openssh"
 mkdir -p ${OPENSSH}/app/src/main/cpp/
 mv ${OPENSSH_VERSION} ${OPENSSH}/app/src/main/cpp/openssh
 
-# Prep openssh
+# Prepare a new repo
 cd ${OPENSSH}
-echo -e "${GATRR}" >.gitattributes
-git init .
+printf "%b" "${GATRR}" > .gitattributes
+git init -b dev .
 git add * .gitattributes
 git commit -a -m "${OPENSSH_VERSION}"
 cd ${SRC_ROOT}
@@ -188,10 +224,9 @@ autoreconf
 ./configure --host ${ANDROID_TARGET} --disable-lastlog --disable-utmp --disable-wtmp \
             --enable-largefile --without-openssl
 
-# ISSUE THE NEXT SET OF COMMANDS FROM THE TERMINAL INSIDE STUDIO
-# IF YOU ARE NOT THERE YET.
-
+# Switching to the project for merging.
 cd ${PROJECT_ROOT}
+
 # Add remote: "upstream-openssh" pointing to the location used above
 git remote add upstream-openssh ${SRC_ROOT}/${OPENSSH}
 
@@ -214,18 +249,19 @@ git merge --allow-unrelated-histories upstream-openssh/dev
 # ############################################################################
 
 cd ${SRC_ROOT}
-wget ${DROPBEAR_DOWNLOAD}
-unzip x -so ${DROPBEAR_VERSION}* | tar xf -
+export DROPBEAR="upstream-dropbear"
+
+wget "${DROPBEAR_DOWNLOAD}" || { echo "Download failed. Exiting."; exit 1; }
+tar xf ${DROPBEAR_VERSION}.tar.bz2
 
 # rename the directory so we don't need to change the git remote names
-export DROPBEAR="upstream-dropbear"
 mkdir -p ${DROPBEAR}/app/src/main/cpp/
 mv ${DROPBEAR_VERSION} ${DROPBEAR}/app/src/main/cpp/dropbear
 
-# Prep dropbear
+# Prepare a new repo
 cd ${DROPBEAR}
-echo -e "${GATRR}" >.gitattributes
-git init .
+printf "%b" "${GATRR}" > .gitattributes
+git init -b dev .
 # ignore warnings about txt files in "rsa-testvectors"
 git add * .gitattributes
 git commit -a -m "${DROPBEAR_VERSION}"
@@ -237,18 +273,14 @@ cd ${SRC_ROOT}/${DROPBEAR}/app/src/main/cpp/dropbear
             --disable-utmp --disable-wtmp \
             --enable-bundled-libtom --enable-largefile
 
-# ISSUE THE NEXT SET OF COMMANDS FROM THE TERMINAL INSIDE STUDIO
-# IF YOU ARE NOT THERE YET.
-
-# Now switch to the ssh4d project and merge the remote from above
+# Switching to the project for merging.
 cd ${PROJECT_ROOT}
+
 # Add remote: "upstream-dropbear" pointing to the location used above
 git remote add upstream-dropbear ${SRC_ROOT}/${DROPBEAR}
 
-# pull the new code
+# pull the new code and merge
 git fetch upstream-dropbear
-
-# finally merge
 git merge --allow-unrelated-histories upstream-dropbear/dev
 
 #    Merge and solve conflicts as usual.
